# ===============================

# SERVER

# ===============================

server.port=8080

# ===============================

# H2 DATABASE CONFIGURATION

# ===============================

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================

# JPA / HIBERNATE

# ===============================

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# create, create-drop, update, validate

spring.jpa.hibernate.ddl-auto=update

# SQL loglar? göst?rsin

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================

# H2 CONSOLE (BRAUZERD? AÇMAQ ÜÇÜN)

# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================

# DATA INITIALIZATION (optional)

# ===============================

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
